---
title: "Weekly Update"
author: "Erin Feichtinger"
date: "Monday, April 18, 2016"
output: html_document
---

### Brief summary of meeting last week
We mainly talked about the manuscript and the changes to make. Some aestetic features on the figures need to be adjusted. I've been going through Bruce's comments and editing as I go. I made some figures showing the relationship the growth rate and lambda, net reproductive rate, and generation time for a monotypic population. They are non-linear relationships (although they are only slightly curved).

We also talked about plotting d(lambda)/d(sigma) as a function of R0 and T and plotting the second eigenvalue for phi = -0.3,0,0.5 and 0.9 (same as the other figures).

We also spend some time discussing how to incorporate Vindenes 2015 paper in the introduction and discussion. Lastly, we talked about what journal we want to submit the manuscript to. Our first choice is Ecology Letters but plans B and c are Theoretical Ecology and Evolutionary Ecology Research. 


### Plots for the monotypic population as requested by Bruce's long comment on the manuscript

These are not necessarily meant for publication; they are more like exploratory figures to aid in explaining the results in the special case of monotypic populations (or where phi = 1).

```{r, echo=FALSe}
#Single type pop, all parameters fixed except for g (so sigma or phi)
#Parameters: s = 0.5, F = 1, P = 0.7 

#g = 0.1
g1 <- matrix(c(0.45,1,0.05,0.7), nrow=2, ncol=2, byrow=TRUE)
#g = 0.2
g2 <- matrix(c(0.4,1,0.1,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.3
g3 <- matrix(c(0.35,1,0.15,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.4
g4 <- matrix(c(0.3,1,0.2,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.5
g5 <- matrix(c(0.25,1,0.25,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.6
g6 <- matrix(c(0.2,1,0.3,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.7
g7 <- matrix(c(0.15,1,0.35,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.8
g8 <- matrix(c(0.1,1,0.4,0.7), nrow =2, ncol=2, byrow=TRUE)
#g = 0.9
g9 <- matrix(c(0.05,1, 0.45,0.7), nrow =2, ncol=2, byrow=TRUE)

eig1 <- lambda(g1)
eig2 <- lambda(g2)
eig3 <- lambda(g3)
eig4 <- lambda(g4)
eig5 <- lambda(g5)
eig6 <- lambda(g6)
eig7 <- lambda(g7)
eig8 <- lambda(g8)
eig9 <- lambda(g9)

lam <- c(eig1,eig2,eig3,eig4,eig5,eig6,eig7,eig8,eig9)

r1 <- net.reproductive.rate(g1)
r2 <- net.reproductive.rate(g2)
r3 <- net.reproductive.rate(g3)
r4 <- net.reproductive.rate(g4)
r5 <- net.reproductive.rate(g5)
r6 <- net.reproductive.rate(g6)
r7 <- net.reproductive.rate(g7)
r8 <- net.reproductive.rate(g8)
r9 <- net.reproductive.rate(g9)

net.rep <- c(r1,r2,r3,r4,r5,r6,r7,r8,r9)

t1 <- generation.time(g1)
t2 <- generation.time(g2)
t3 <- generation.time(g3)
t4 <- generation.time(g4)
t5 <- generation.time(g5)
t6 <- generation.time(g6)
t7 <- generation.time(g7)
t8 <- generation.time(g8)
t9 <- generation.time(g9)

time <- c(t1,t2,t3,t4,t5,t6,t7,t8,t9)

df <- data.frame(lam,net.rep,time)
df["g"] <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)

##Plots to see lambda, R0, and T as a function of g in a monotypic population
library(ggplot2)
qplot(df$g,df$egs)
qplot(df$g,df$rs)
qplot(df$g,df$ts)

plotA <- ggplot(df, aes(g, lam))
plotA + geom_point(colour = "black", size = 3) + xlim(0.1,0.9) +
  ylim(0.8,1.2) + labs(x = expression(gamma), y = expression(lambda)) 

plotB <- ggplot(df, aes(g, net.rep))
plotB + geom_point(colour = "black", size=3) + xlim(0.1,0.9) +
  ylim(0.3,1.7) + labs(x = expression(gamma), y = expression("R"[0]))

plot.t <- ggplot(df, aes(g, time))
plot.t + geom_point(colour="black", size=3) + xlim(0.1,0.9) +
  ylim(4,6.5) + labs(x= expression(gamma), y = expression("T"[1]))

```

### Some questions just to make sure things are clear 

1. I took Bruce's comments to mean that a monotypic population is just one type so no phi or sigma, just g, s, P and F. Is this correct?
2. The matplots that I previously made to show the time it takes for the population to reach a stable stage distribution. For the two type population, I treated fast and slow as two subpopulations where all offspring match the phenotype of their parents' exactly (so, phi = 1 here). In this case, I set sigma to 0.05 to see what happens with fast and slow separetly. Was this not the correct way to think about this? Does this even make sense to do? 

2. So, with that in mind, do we stil want a figure showing the convergence of each stage (juvenile and adult) to the SSD for fast and slow? 

3. I'm not sure I understand Bruce's comments regarding the expected time spent in each stage. 

4. Bruce asked if I had thought about doing additional transient analyses and provided the DOI for a paper that I have read this past winter. My sense was that the damping ratio calculations and the matplots showing the time it takes for convergence to SSD was sufficient. 

5. In general, I feel that Gordon's ideas about the paper are slightly different than Bruce's ideas (or perhaps they are the same but communicated in a different way). If possible, I would really like the three of us to talk. I feel that I am getting pulled in two different directions, especially with regard to the transient dynamics and the expected stage durations. 
