---
title: "After Meeting 5/31"
author: "Erin Feichtinger"
date: "June 3, 2016"
output: pdf_document
---

```{r, echo = FALSE}
library(ggplot2)
# May 3 2016, S = 0.4 
# Read in data from output 
#new.data <- write.csv(eig.dat, file= "May3b.csv")
new.data <- read.csv("May3b.csv", header=TRUE)
names(new.data) <- c("X", "gamma","S","sigma","lam","eigen2","phi",
            "r","R0","damp","time","ages","agef")

# May 10 2016, S = 0.5 & 0.6 
# Read in data from output
data.56 <- read.csv("May10.csv", header = TRUE)
names(data.56) <- c("X", "gamma","S","sigma","lam","eigen2","phi",
                    "r","R0","damp","time","ages","agef")

#### June 3 2016
# Subset data where sigma = 0 to see relationship between g and lambda, R0, T
# Using data.56 and new.data
no.sig4 <- subset(new.data, sigma ==0)
no.sig5 <- subset(data.56, sigma == 0 & S == 0.5)
no.sig6 <- subset(data.56, sigma == 0 & S == 0.6)

## plots 

# Lambda
ggplot() + 
  geom_line(data=no.sig5, aes(x=gamma, y=lam), color = "green") +
  geom_line(data=no.sig6, aes(x =gamma, y=lam), color= "blue") +
  geom_line(data=no.sig4, aes(x=gamma, y=lam), color= "red") +
  labs(x=expression(gamma), y =expression(lambda)) 

ggplot() + 
  geom_line(data=no.sig5, aes(x=gamma, y=R0), color = "green") +
  geom_line(data=no.sig6, aes(x =gamma, y=R0), color= "blue") +
  geom_line(data=no.sig4, aes(x=gamma, y=R0), color= "red") +
  labs(x=expression(gamma), y = "R0") 

ggplot() +
  geom_line(data=no.sig5, aes(x=gamma, y=time), color = "green") +
  geom_line(data=no.sig6, aes(x =gamma, y=time), color= "blue") +
  geom_line(data=no.sig4, aes(x=gamma, y=time), color= "red") +
  labs(x=expression(gamma), y = "Generation time")

```

There is a way for ggplot2 to automatically make a legend but I ran into some trouble rearraning the data so it would work and I didn't want to take hours to figure it out today. So, here are some basic graphs with 3 values of S, juvenile survival (0.4, 0.5, 0.6). 

The red line is S = 0.4, green is S = 0.5 and blue is S = 0.6. Even though they are simple plots with only 3 values of S, you can still see the patterns of the relationship between gamma (growth probability) and lambda, R0 and T when sigma = 0. 

### Now for the summary of our skype meeting 

As I understand it, The paper that I have written is its current state is very far from being finished in the sense that everything I have written is “preliminary” and not the real results or real story that we are trying to convey here. Specifically, the current results section should be trashed, along with all figures with the possible exception of Figure 2. The discussion section as it currently stands is wrong and will need to be rewritten. So to sum up, I’ve wasted a lot of time chasing geese when I should have been pursuing a different direction this whole time. The implication of this is that the paper will take much longer to be submission ready. When Bruce and Gordon are done traveling, it is necessary that the three of us have a conversation.   

1. What is the fitness of each phenotype? 
2. From the estimation of the expected age at first reproduction, there is an asymmetry between the types - (see Figure 5 in the soon-to-be-trashed and re-written manuscript)
3. Need to calculate R0 for each phenotype, R0 that comes out of the simulation is for the whole population, which includes both types, I don't know how to write formulas for R0 for each phenotype. 
+ I could fix all parameter values and consider each phenotype separately but this is probably the wrong way to approach it 
+ The other way I can think of to find R0 is the life table approach of the sum of lx*mx but I’m guessing not appropriate here
+ I used the popbio package in R with the function net.reproductive.rate, This function estimates R0 using the method of Caswell Section 5.3.4
+ I don’t understand the construction of the R matrix for the killer whale data (shown on pg 127 in Caswell)
+ I don’t understand how to find the entries rij in R which are the expected number of offspring each time step, I tried working through the killer whale example and I couldn’t get the same answers 

4. Understanding the effects of phi
+ Consider the composition of a cohort at birth for different values of phi
+ Also need to consider the adult composition once the initial cohort has matured
+ Then, the next cohort composition will depend on the current adult composition (and phi) 

5. Mean R0 and T between fast and slow
+ Don't know how to do this for cases where phi is non-zero
+ See the equations from Bruce's in-line comment 

6. What is the proportion of adults that are fast? Calculate SSD and pull out both types
+ There is a function for SSD in the popbio package, I had trouble storing the components I want since the output is a 1 x 4 matrix, I think I know how to do this know, however

7. Yea so the graph you sketched at the end, I have no idea what you are talking about. The screenshot I captured is too blurry for me to see anything. I don’t understand how we can find the value of phi that is needed to go from a shrinking to a growing population from F/2 and sigma= 0 

As you can tell, my frustration level is at a maximum. So until the three of us can have a conversation about this, I’m putting this aside until we can talk about it, as one of my other committee members suggested. This whole situation makes me frustrated, angry, raises my anxiety level, drains my motivation and prevents me from being productive in other areas of my work. 

I don’t know what Bruce’s plans for the rest of June are, but Gordon will be back June 15 so perhaps we can aim for a skype meeting in the last two weeks of June 









